#!/usr/bin/env python3
#
# Copyright (C) 2025 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import logging
import os
import sys

from vyos.utils.auth import EPasswdStrength, evaluate_strength


def init_logger() -> logging.Logger:
    logger = logging.getLogger(__name__)
    logger.name = os.path.basename(__file__)
    logger.setLevel(logging.INFO)
    fmt = logging.Formatter('%(levelname)s: %(message)s')
    output = logging.StreamHandler(stream=sys.stderr)
    output.setLevel(logging.INFO)
    output.setFormatter(fmt)
    logger.addHandler(output)

    return logger

def validate() -> None:
    logger = init_logger()

    if len(sys.argv) != 2:
        logger.error("Invalid number of arguments")
        sys.exit(2)
    else:
        result = evaluate_strength(sys.argv[1])

        if result['strength'] == EPasswdStrength.WEAK:
            logger.warning(result['error'])

        sys.exit(0)


if __name__ == '__main__':
    validate()
    # if len(argv) != 2:
    #     print('Error: Invalid number of arguments')
    #     exit(2)
    #
    # check_result = evaluate_strength(argv[1])
    #
    # if check_result['strength'] == EPasswdStrength.WEAK:
    #     # T6353: Just display warning for now.
    #     # Exiting with error breaks the initial config on boot.
    #     print(f'Warning: {check_result["message"]}', file=stdout)
    #     exit(0)
    #
    # exit(0)
